<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>SFC.Game.Messages</PackageId>
    <Version>0.0.5</Version>
    <Authors>Andrii Kryvoruk</Authors>
    <Company>SFC</Company>
    <Product>SFC</Product>
    <PackageTags>Street Football Club;SFC;Game;Messages</PackageTags>
    <Description>
      Messages from Game service for SFC project
    </Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
